language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "sivanWu0222"
  - git config user.email "yirufeng@foxmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - source
env:
 global:
   - GH_REF: github.com/sivanWu0222/sivanWu0222.github.io.git